# Generated by Django 6.0.1 on 2026-02-02 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootballLeagueManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FootballLeagueManagement.season'),
        ),
    ]
