# Generated by Django 6.0.1 on 2026-02-02 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FootballLeagueManagement', '0002_team_season'),
    ]

    operations = [
        # Intentionally left empty: Notice model removed before applying migrations.
    ]
