# Generated by Django 6.0.1 on 2026-02-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootballLeagueManagement', '0003_notice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='entity_id',
        ),
        migrations.RemoveField(
            model_name='fine',
            name='entity_id',
        ),
        migrations.AddField(
            model_name='contract',
            name='entity_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='fine',
            name='entity_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='matchref',
            constraint=models.UniqueConstraint(fields=('match', 'ref_type'), name='unique_match_ref_type'),
        ),
        migrations.AddConstraint(
            model_name='matchref',
            constraint=models.UniqueConstraint(fields=('match', 'ref'), name='unique_match_ref_assign'),
        ),
    ]
