# Generated by Django 6.0.1 on 2026-09-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootballLeagueManagement', '0004_remove_contract_entity_id_remove_fine_entity_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(default='League Admin', max_length=100)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which this rule appears.')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='sponsor_logos/')),
                ('website_url', models.URLField(blank=True, null=True)),
                ('sponsor_type', models.CharField(choices=[('League', 'League Sponsor'), ('Team', 'Team Sponsor')], default='League', max_length=20)),
            ],
        ),
    ]
