# Generated by Django 6.0.1 on 2026-09-21 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootballLeagueManagement', '0006_player_assists_player_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tier', models.PositiveIntegerField(help_text='1 is the top tier (e.g. League A)')),
            ],
            options={
                'ordering': ['tier', 'name'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='report',
            field=models.TextField(blank=True, help_text='Match report and summary.', null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='FootballLeagueManagement.division'),
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField()),
                ('assist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals_assisted', to='FootballLeagueManagement.player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='FootballLeagueManagement.match')),
                ('scorer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals_scored', to='FootballLeagueManagement.player')),
            ],
            options={
                'ordering': ['minute'],
            },
        ),
        migrations.CreateModel(
            name='PromotionRelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Promoted', 'Promoted'), ('Relegated', 'Relegated')], max_length=20)),
                ('from_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_records', to='FootballLeagueManagement.division')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FootballLeagueManagement.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_relegations', to='FootballLeagueManagement.team')),
                ('to_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_records', to='FootballLeagueManagement.division')),
            ],
        ),
    ]
