# Generated by Django 6.0.1 on 2026-09-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootballLeagueManagement', '0007_division_match_report_team_division_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_own_goal',
            field=models.BooleanField(default=False),
        ),
    ]
