# Generated by Django 6.0.1 on 2026-09-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootballLeagueManagement', '0008_goal_is_own_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('GOALKEEPER (GK)', 'GOALKEEPER (GK)'), ('Centre-Back (CB)', 'Centre-Back (CB)'), ('Full-Back (LB / RB)', 'Full-Back (LB / RB)'), ('Defensive Midfielder (CDM)', 'Defensive Midfielder (CDM)'), ('Central Midfielder (CM)', 'Central Midfielder (CM)'), ('Attacking Midfielder (CAM)', 'Attacking Midfielder (CAM)'), ('Winger (LM / RM / LW / RW)', 'Winger (LM / RM / LW / RW)'), ('Centre Forward (CF / ST)', 'Centre Forward (CF / ST)')], max_length=50),
        ),
    ]
