# Generated by Django 6.0.1 on 2026-09-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootballLeagueManagement', '0009_alter_player_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='suspension_matches',
            field=models.PositiveIntegerField(blank=True, help_text='Number of matches suspended (e.g., 3 for Red). Can be reduced upon appeal.', null=True),
        ),
    ]
