# Generated by Django 6.0.1 on 2026-09-24 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootballLeagueManagement', '0010_card_suspension_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='current_match_week',
            field=models.PositiveIntegerField(default=1, help_text='Current match week/matchday for this season.'),
        ),
        migrations.CreateModel(
            name='PointDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_deducted', models.PositiveIntegerField()),
                ('reason', models.CharField(help_text="Reason for deduction (e.g., 'using unregistered player')", max_length=255)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FootballLeagueManagement.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_deductions', to='FootballLeagueManagement.team')),
            ],
        ),
    ]
