# Generated by Django 6.0.1 on 2026-09-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootballLeagueManagement', '0011_season_current_match_week_pointdeduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
